name: Interchain Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-start-cosmos-chain:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: checkout code
        uses: actions/checkout@v3

      - run: make ictest-start-cosmos

  test-start-polkadot-chain:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: checkout code
        uses: actions/checkout@v3

      - run: make ictest-start-polkadot

  # test-ibc-transfer:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Go 1.19
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.19

  #     - name: checkout code
  #       uses: actions/checkout@v3

  #     - run: make ictest-ibc

  test-push-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: checkout code
        uses: actions/checkout@v3

      - run: make ictest-push-wasm